# GitHub Labels Configuration

labels:
  # Type labels
  - name: bug
    color: d73a4a
    description: Something isn't working

  - name: enhancement
    color: a2eeef
    description: New feature or request

  - name: documentation
    color: 0075ca
    description: Improvements or additions to documentation

  - name: performance
    color: f97316
    description: Performance improvements needed

  # Priority labels
  - name: priority:critical
    color: b60205
    description: Critical priority - immediate attention required

  - name: priority:high
    color: d93f0b
    description: High priority

  - name: priority:medium
    color: fbca04
    description: Medium priority

  - name: priority:low
    color: 0e8a16
    description: Low priority

  # Status labels
  - name: needs-triage
    color: ededed
    description: Needs initial triage

  - name: needs-review
    color: fbca04
    description: Needs code review

  - name: needs-testing
    color: d4c5f9
    description: Needs testing before merge

  - name: in-progress
    color: 1d76db
    description: Work in progress

  - name: blocked
    color: d73a4a
    description: Blocked by other issues

  # Game phase labels
  - name: phase-1
    color: 0e8a16
    description: Phase 1 - Core Mechanics

  - name: phase-2
    color: 1d76db
    description: Phase 2 - Animation & VFX

  - name: phase-3
    color: 5319e7
    description: Phase 3 - Advanced FPS

  - name: phase-4
    color: e99695
    description: Phase 4 - Advanced Gameplay

  # Game mode labels
  - name: mode:rts
    color: c5def5
    description: RTS (Commander View) related

  - name: mode:fps
    color: f9d0c4
    description: FPS (Field Operative View) related

  - name: mode:both
    color: bfdadc
    description: Affects both game modes

  # Component labels
  - name: component:ui
    color: d4c5f9
    description: UI/UX components

  - name: component:3d
    color: c2e0c6
    description: 3D graphics and rendering

  - name: component:audio
    color: fef2c0
    description: Audio and sound effects

  - name: component:ai
    color: bfd4f2
    description: AI and pathfinding

  - name: component:physics
    color: d1bcf9
    description: Physics and ballistics

  - name: component:networking
    color: c5def5
    description: Multiplayer networking

  # Platform labels
  - name: platform:ios
    color: 0366d6
    description: iOS specific

  - name: platform:simulator
    color: 84b6eb
    description: iOS Simulator specific

  # CI/CD labels
  - name: ci/cd
    color: 0e8a16
    description: CI/CD and automation

  - name: dependencies
    color: 0366d6
    description: Dependency updates

  # Special labels
  - name: good first issue
    color: 7057ff
    description: Good for newcomers

  - name: help wanted
    color: 008672
    description: Extra attention is needed

  - name: question
    color: d876e3
    description: Further information is requested

  - name: wontfix
    color: ffffff
    description: This will not be worked on

  - name: duplicate
    color: cfd3d7
    description: This issue or pull request already exists

  - name: invalid
    color: e4e669
    description: This doesn't seem right
